---
- name:         Get list of services.
  register:     openstack_services
  changed_when: no
  command:      openstack service list -f value -c Name

- name:         Assign service.
  command:      openstack service create --name glance --description "Openstack Image" image
  when:         '"glance" not in openstack_services.stdout'
