---
- name:         Get list of users.
  register:     openstack_users
  changed_when: no
  command:      openstack user list -f value -c Name --domain default

- name:    Create users.
  command: 'openstack user create --domain default --password {{ glance_password }} glance'
  when:    '"glance" not in openstack_users.stdout'
