---
- name:         Get list of Image endpoints
  register:     openstack_image_endpoints
  changed_when: no
  command:      openstack endpoint list -f value -c Interface --service compute 

- name:    Create Compute endpoints
  command: 'openstack endpoint create --region {{ region }} compute {{ item.key }} {{ item.value }}'
  when:    '"{{ item.key }}" not in openstack_image_endpoints.stdout'
  with_dict:
    public:   'http://{{ nova_host }}:8774/v2.1/%(tenant_id)s'
    internal: 'http://{{ nova_host }}:8774/v2.1/%(tenant_id)s'
    admin:    'http://{{ nova_host }}:8774/v2.1/%(tenant_id)s'
