---
- name: Setup mariaDB
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - mariadb
    - mariadb-server
    - python2-PyMySQL
    - MySQL-python

- name: Configure mariaDB
  ini_file:
    dest: /etc/my.cnf.d/openstack.cnf
    section: mysqld
    option: '{{ item.key }}'
    value:  '{{ item.value }}'
  with_dict:
    bind_address:           '{{ ip_address }}'
    default-storage-engine: innodb
    max_connections:        4096
    collation-server:       utf8_general_ci
    character-set-server:   utf8

- name: enabled mariaDB
  command: systemctl enable mariadb.service

- name: start mariaDB
  command: systemctl start mariadb.service

- name: update mysql root password for all root accounts
  mysql_user:
    login_user:     root
    login_password: ''
    login_host:     localhost
    name: root
    host: localhost
    password: '{{ mysql_password }}'
